// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: coverage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DateRange holds the earliest and latest observed date for a coverage key.
type DateRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Earliest      string                 `protobuf:"bytes,1,opt,name=earliest,proto3" json:"earliest,omitempty"`
	Latest        string                 `protobuf:"bytes,2,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateRange) Reset() {
	*x = DateRange{}
	mi := &file_coverage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateRange) ProtoMessage() {}

func (x *DateRange) ProtoReflect() protoreflect.Message {
	mi := &file_coverage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateRange.ProtoReflect.Descriptor instead.
func (*DateRange) Descriptor() ([]byte, []int) {
	return file_coverage_proto_rawDescGZIP(), []int{0}
}

func (x *DateRange) GetEarliest() string {
	if x != nil {
		return x.Earliest
	}
	return ""
}

func (x *DateRange) GetLatest() string {
	if x != nil {
		return x.Latest
	}
	return ""
}

// EntityRanges maps entity dcids to their date range for a given variable.
type EntityRanges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        map[string]*DateRange  `protobuf:"bytes,1,rep,name=entity,proto3" json:"entity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // entityDcid -> range
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRanges) Reset() {
	*x = EntityRanges{}
	mi := &file_coverage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRanges) ProtoMessage() {}

func (x *EntityRanges) ProtoReflect() protoreflect.Message {
	mi := &file_coverage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRanges.ProtoReflect.Descriptor instead.
func (*EntityRanges) Descriptor() ([]byte, []int) {
	return file_coverage_proto_rawDescGZIP(), []int{1}
}

func (x *EntityRanges) GetEntity() map[string]*DateRange {
	if x != nil {
		return x.Entity
	}
	return nil
}

// VariableCoverageRequest specifies the variables (and optionally entities) to
// look up in the precomputed coverage map.
type VariableCoverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variables     []string               `protobuf:"bytes,1,rep,name=variables,proto3" json:"variables,omitempty"`
	Entities      []string               `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableCoverageRequest) Reset() {
	*x = VariableCoverageRequest{}
	mi := &file_coverage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableCoverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableCoverageRequest) ProtoMessage() {}

func (x *VariableCoverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coverage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableCoverageRequest.ProtoReflect.Descriptor instead.
func (*VariableCoverageRequest) Descriptor() ([]byte, []int) {
	return file_coverage_proto_rawDescGZIP(), []int{2}
}

func (x *VariableCoverageRequest) GetVariables() []string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *VariableCoverageRequest) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

// VariableCoverageResponse contains the variable-level envelope and, when
// entities were requested, the per-(variable,entity) date ranges.
// Absent variables and absent {entity,variable} pairs are omitted.
type VariableCoverageResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	VariableCoverage map[string]*DateRange    `protobuf:"bytes,1,rep,name=variable_coverage,json=variableCoverage,proto3" json:"variable_coverage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // varDcid -> envelope
	EntityCoverage   map[string]*EntityRanges `protobuf:"bytes,2,rep,name=entity_coverage,json=entityCoverage,proto3" json:"entity_coverage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // varDcid -> {entityDcid -> range}
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VariableCoverageResponse) Reset() {
	*x = VariableCoverageResponse{}
	mi := &file_coverage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableCoverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableCoverageResponse) ProtoMessage() {}

func (x *VariableCoverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coverage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableCoverageResponse.ProtoReflect.Descriptor instead.
func (*VariableCoverageResponse) Descriptor() ([]byte, []int) {
	return file_coverage_proto_rawDescGZIP(), []int{3}
}

func (x *VariableCoverageResponse) GetVariableCoverage() map[string]*DateRange {
	if x != nil {
		return x.VariableCoverage
	}
	return nil
}

func (x *VariableCoverageResponse) GetEntityCoverage() map[string]*EntityRanges {
	if x != nil {
		return x.EntityCoverage
	}
	return nil
}

var File_coverage_proto protoreflect.FileDescriptor

const file_coverage_proto_rawDesc = "" +
	"\n" +
	"\x0ecoverage.proto\x12\vdatacommons\"?\n" +
	"\tDateRange\x12\x1a\n" +
	"\bearliest\x18\x01 \x01(\tR\bearliest\x12\x16\n" +
	"\x06latest\x18\x02 \x01(\tR\x06latest\"\xa0\x01\n" +
	"\fEntityRanges\x12=\n" +
	"\x06entity\x18\x01 \x03(\v2%.datacommons.EntityRanges.EntityEntryR\x06entity\x1aQ\n" +
	"\vEntityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.datacommons.DateRangeR\x05value:\x028\x01\"S\n" +
	"\x17VariableCoverageRequest\x12\x1c\n" +
	"\tvariables\x18\x01 \x03(\tR\tvariables\x12\x1a\n" +
	"\bentities\x18\x02 \x03(\tR\bentities\"\xa3\x03\n" +
	"\x18VariableCoverageResponse\x12h\n" +
	"\x11variable_coverage\x18\x01 \x03(\v2;.datacommons.VariableCoverageResponse.VariableCoverageEntryR\x10variableCoverage\x12b\n" +
	"\x0fentity_coverage\x18\x02 \x03(\v29.datacommons.VariableCoverageResponse.EntityCoverageEntryR\x0eentityCoverage\x1a[\n" +
	"\x15VariableCoverageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.datacommons.DateRangeR\x05value:\x028\x01\x1a\\\n" +
	"\x13EntityCoverageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.datacommons.EntityRangesR\x05value:\x028\x01B0Z.github.com/datacommonsorg/mixer/internal/protob\x06proto3"

var (
	file_coverage_proto_rawDescOnce sync.Once
	file_coverage_proto_rawDescData []byte
)

func file_coverage_proto_rawDescGZIP() []byte {
	file_coverage_proto_rawDescOnce.Do(func() {
		file_coverage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coverage_proto_rawDesc), len(file_coverage_proto_rawDesc)))
	})
	return file_coverage_proto_rawDescData
}

var file_coverage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coverage_proto_goTypes = []any{
	(*DateRange)(nil),                // 0: datacommons.DateRange
	(*EntityRanges)(nil),             // 1: datacommons.EntityRanges
	(*VariableCoverageRequest)(nil),  // 2: datacommons.VariableCoverageRequest
	(*VariableCoverageResponse)(nil), // 3: datacommons.VariableCoverageResponse
	nil,                              // 4: datacommons.EntityRanges.EntityEntry
	nil,                              // 5: datacommons.VariableCoverageResponse.VariableCoverageEntry
	nil,                              // 6: datacommons.VariableCoverageResponse.EntityCoverageEntry
}
var file_coverage_proto_depIdxs = []int32{
	4, // 0: datacommons.EntityRanges.entity:type_name -> datacommons.EntityRanges.EntityEntry
	5, // 1: datacommons.VariableCoverageResponse.variable_coverage:type_name -> datacommons.VariableCoverageResponse.VariableCoverageEntry
	6, // 2: datacommons.VariableCoverageResponse.entity_coverage:type_name -> datacommons.VariableCoverageResponse.EntityCoverageEntry
	0, // 3: datacommons.EntityRanges.EntityEntry.value:type_name -> datacommons.DateRange
	0, // 4: datacommons.VariableCoverageResponse.VariableCoverageEntry.value:type_name -> datacommons.DateRange
	1, // 5: datacommons.VariableCoverageResponse.EntityCoverageEntry.value:type_name -> datacommons.EntityRanges
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_coverage_proto_init() }
func file_coverage_proto_init() {
	if File_coverage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coverage_proto_rawDesc), len(file_coverage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coverage_proto_goTypes,
		DependencyIndexes: file_coverage_proto_depIdxs,
		MessageInfos:      file_coverage_proto_msgTypes,
	}.Build()
	File_coverage_proto = out.File
	file_coverage_proto_goTypes = nil
	file_coverage_proto_depIdxs = nil
}
